apiVersion: v1
kind: Service
metadata:
  name: ethereumtransactionsearch-service
spec:
  selector:
    app: ethereumtransactionsearch-pod
  ports:
  - port: 8000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereumtransactionsearch-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ethereumtransactionsearch-pod
  template:
    metadata:
      labels:
        app: ethereumtransactionsearch-pod
    spec:
      containers:
      - name: ethereumtransactionsearch-container
        image: ethereumtransactionsearch:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
